#
# setup redis
#
- name: install redis
  yum:
    name: "{{ redis_packages }}"
    enablerepo: ius-testing
    state: present
  notify:
    - restart redis

- name: enable redis
  service:
    name: redis
    state: started
    enabled: yes
