#
# setup redis
#
- name: install redis
  yum:
    name: "{{ item }}"
    enablerepo: ius-testing
    state: present
  with_items: "{{ redis_packages }}"
  notify:
    - restart redis

- name: enable redis
  service:
    name: redis
    state: started
    enabled: yes
